### ISSUE TITLE
CS Chip Select

### ISSUE THREAD

**Issue by pimium** [saleae/spi-analyzer#10]
# Chip Select state 
Will be fine to know other the CS is Low or High
```
59.631010920000001,SPI,MOSI: 0x46;  MISO: 0x00
59.631012859999998,SPI,MOSI: 0x00;  MISO: 0x00
59.631014819999997,SPI,CS:0x00
59.631016760000001,SPI,MOSI: 0x01;  MISO: 0x00
59.631018699999998,SPI,MOSI: 0x00;  MISO: 0x00
59.631020640000003,SPI,CS: 0x01
59.631022580000000,SPI,MOSI: 0x00;  MISO: 0x00
```
In the transcript we see only the bytes send. Will be better to have a possibility to detect each transfert.

**Comment by pimium** [comment]
@timreyes already points the issue, he proposes to add "packet id"

**Comment by pimium** [comment]
The probleme happen when you export all the analyzer together

**Comment by timreyes** [comment]
Thanks for letting us know this issue.

I also posted an idea post here:
https://ideas.saleae.com/b/feature-requests/packet-id-doesnt-work-properly/

We'll continue tracking using need for it in that idea post before committing it to the roadmap.

**Comment by timreyes** [comment]
By the way, I also added a comment for you in the idea post I shared earlier!
